---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: db5-cars-lab
 namespace: telco-gitops
spec:
  generators:
    - git:
        directories:
          - path: clusters/mgmt/db5.cars.lab/config-*
        repoURL: 'CHANGEME'
        revision: HEAD
  template:
    metadata:
      name: '00-db5-{{path.basename}}'
      namespace: telco-gitops
    spec:
      destination:
        namespace: telco-gitops
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: 'CHANGEME'
        targetRevision: HEAD
